name: Build releases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build     
    
    runs-on : windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Add SDK when building under Windows
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2019-workload-vctools
        shell: cmd
      
      - name: Build client
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          ./gradlew clientNativeImage
        shell: cmd

      
      - name: Build daemon
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          ./gradlew daemonNativeImage
        shell: cmd
      
      - name: Package executables
        id: package-executables
        run: |
          zip --junk-paths ranflood-alpha.zip .\build\graal\*
