# /********************************************************************************
# * Copyright 2021-2024 (C) by Saverio Giallorenzo <saverio.giallorenzo@gmail.com>*
# *                                                                               *
# * This program is free software; you can redistribute it and/or modify          *
# * it under the terms of the GNU Library General Public License as               *
# * published by the Free Software Foundation; either version 2 of the            *
# * License, or (at your option) any later version.                               *
# *                                                                               *
# * This program is distributed in the hope that it will be useful,               *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of                *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                 *
# * GNU General Public License for more details.                                  *
# *                                                                               *
# * You should have received a copy of the GNU Library General Public             *
# * License along with this program; if not, write to the                         *
# * Free Software Foundation, Inc.,                                               *
# * 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.                     *
# *                                                                               *
# * For details about the authors of this software, see the AUTHORS file.         *
# *********************************************************************************/

name: Build releases

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of release'
        required: true
        default: 'v.0.1-alpha'

jobs:
  create_release:
    permissions: write-all
    name: create_release
    runs-on: [ubuntu-latest]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag: ${{ github.event.inputs.name }}
    steps:
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
      - name: Check out code
        uses: actions/checkout@v1
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.name }}
          release_name: Release ${{ github.event.inputs.name }}
          draft: false
          prerelease: false

  build_and_upload:
    needs: [create_release]
    name: build and upload
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on : ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21 
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # - name: Add SDK when building under Windows
      #   if: runner.os == 'Windows'
      #   run: |
      #     choco install visualstudio2017-workload-vctools
      #   shell: cmd
    
      - name: Build jars (Linux only)
        if: runner.os == 'Linux'
        run: |
          ./gradlew jar

      - name: Build client
        run: ./gradlew clientNativeImage
      
      - name: Build daemon
        run: ./gradlew daemonNativeImage
          
      - name: Package executables (*nix)
        id: package-executables
        if: runner.os == 'Linux' || runner.os == 'MacOs'
        run: |
          zip --junk-paths ranflood.zip build/graal/*
      
      - name: Package executables (windows)
        id: package-executables-win
        if: runner.os == 'Windows'
        run: |
          powershell Compress-Archive build\graal\* ranflood.zip
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ranflood.zip
          asset_name: ranflood-${{ needs.create_release.outputs.tag }}_${{ runner.os }}.zip
          asset_content_type: application/zip
          
      - name: Package jar executables
        if: runner.os == 'Linux'
        run: |
          zip --junk-paths ranflood-jar.zip build/libs/*
          
      - name: Upload Jar Release Asset
        if: runner.os == 'Linux'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ranflood-jar.zip
          asset_name: ranflood-${{ needs.create_release.outputs.tag }}_all.zip
          asset_content_type: application/zip
